# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.firefox.options import Options

class TestSmokeTest():
  def setup_method(self, method):
    options = Options()
    options.add_argument("--headless=new")  # headless Firefox
    options.add_argument("--no-sandbox")     # for CI
    options.add_argument("--disable-dev-shm-usage")  # optional but good for CI
    self.driver = webdriver.Firefox(options=options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1HomePage(self):
    self.driver.get("http://127.0.0.1:5501/teton/1.6/index.html")
    self.driver.set_window_size(1346, 1012)
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".header-logo img")
    assert len(elements) > 0
    assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h1").text == "Teton Idaho"
    assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h2").text == "Chamber of Commerce"
    assert self.driver.title == "Teton Idaho CoC"
  
  def test_test2HomePage(self):
    self.driver.get("http://127.0.0.1:5501/teton/1.6/index.html")
    self.driver.set_window_size(1613, 880)
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".spotlight1 img")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".spotlight2 img")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.LINK_TEXT, "Join Us!")
    assert len(elements) > 0
    assert self.driver.find_element(By.LINK_TEXT, "Join").text == "Join"
  
  def test_test3DirectoryPage(self):
    self.driver.get("http://127.0.0.1:5501/teton/1.6/index.html")
    self.driver.set_window_size(1613, 880)
    self.driver.find_element(By.LINK_TEXT, "Directory").click()
    self.driver.find_element(By.ID, "directory-grid").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".gold-member:nth-child(9) > p:nth-child(2)")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "directory-list").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".gold-member:nth-child(9) > p:nth-child(2)").text == "Teton Turf and Tree"
  
  def test_test4JoinPage(self):
    self.driver.get("http://127.0.0.1:5501/teton/1.6/index.html")
    self.driver.set_window_size(1613, 880)
    self.driver.find_element(By.LINK_TEXT, "Join").click()
    elements = self.driver.find_elements(By.NAME, "fname")
    assert len(elements) > 0
    self.driver.find_element(By.NAME, "fname").click()
    self.vars["James"] = self.driver.execute_script("document.getElementsByName(\'fname\')[0].value = \'James\'")
    self.driver.find_element(By.NAME, "fname").click()
    self.driver.find_element(By.NAME, "lname").click()
    self.vars["De Guzman"] = self.driver.execute_script("document.getElementsByName(\'lname\')[0].value = \'De Guzman\'")
    self.driver.find_element(By.NAME, "bizname").click()
    self.vars["besystech"] = self.driver.execute_script("document.getElementsByName(\'bizname\')[0].value = \'besystech\'")
    self.driver.find_element(By.NAME, "biztitle").click()
    self.vars["Programmer"] = self.driver.execute_script("document.getElementsByName(\'biztitle\')[0].value = \'Programmer\'")
    self.driver.find_element(By.NAME, "submit").click()
    elements = self.driver.find_elements(By.NAME, "email")
    assert len(elements) > 0
  
  def test_test5AdminPage(self):
    self.driver.get("http://127.0.0.1:5501/teton/1.6/admin.html")
    self.vars["James123"] = self.driver.execute_script("document.getElementsByName(\'username\')[0].value = \'James123\'")
    self.vars["1234"] = self.driver.execute_script("document.getElementsByName(\'password\')[0].value = \'1234\'")
    self.driver.find_element(By.CSS_SELECTOR, "input[value=\"Login\"]").click()
    value = self.driver.find_element(By.NAME, "username").get_attribute("value")
    assert value == "James123"
    assert self.driver.find_element(By.CSS_SELECTOR, ".errorMessage").text == "Invalid username and password."
  
